from unicorn import *

UNICORN_ACCESS_STR = {
    UC_MEM_READ : "UC_MEM_READ",
    UC_MEM_WRITE : "UC_MEM_WRITE",
    UC_MEM_FETCH : "UC_MEM_FETCH",
    UC_MEM_READ_UNMAPPED : "UC_MEM_READ_UNMAPPED",
    UC_MEM_WRITE_UNMAPPED : "UC_MEM_WRITE_UNMAPPED",
    UC_MEM_FETCH_UNMAPPED : "UC_MEM_FETCH_UNMAPPED",
    UC_MEM_WRITE_PROT : "UC_MEM_WRITE_PROT",
    UC_MEM_READ_PROT : "UC_MEM_READ_PROT",
    UC_MEM_FETCH_PROT : "UC_MEM_FETCH_PROT",
    UC_MEM_READ_AFTER : "UC_MEM_READ_AFTER",
}